version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: jhonatanraulhub/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: jhonatanraulhub/nginx-jhow:prod
    container_name: nginx-jhow
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge